import Head from "next/head";
import { useRouter } from "next/router";
import { useSearchParams } from "next/navigation";
import VirtualMeet from "../../VirtualMeet";

export default function Join() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const name = searchParams.get("name");

  return (
    <>
      <Head>
        <title>WebRTC - Video Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VirtualMeet
        myname={name}
        roomName={router.query.slug}
        apiEventNotify={(obj) => {
          console.log(obj);
          if (
            obj.eventType === "endCall" ||
            obj.eventType === "endCallForAll"
          ) {
            router.push("/");
          }
        }}
      />
    </>
  );
}
